on:
  push:
    branches:
      - main  # Mantenha 'main' se essa for sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact (index.html, style.css)
        uses: actions/upload-pages-artifact@v3
        with:
          # O ponto ('.') indica que o conteúdo a ser publicado está na raiz do repositório.
          path: '.' 

      - name: Deploy automático
        id: deployment
        uses: actions/deploy-pages@v4
